services:
  medication:
    build:
      context: ./medication
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console

  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  medication-ui:
    build:
      context: ./medication-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - medication
      - product
  # github-runner:
  #   image: myoung34/github-runner:latest
  #   restart: always
  #   environment:
  #     - REPO_URL=https://github.com/pablo092/mbsoftchallenge
  #     - RUNNER_NAME=docker-runner
  #     - RUNNER_TOKEN=AEFKH4PUCMJFKSXSGQL4KL3HY4KD4
  #     - LABELS=self-hosted
  #     - RUNNER_WORKDIR=/tmp/github-runner
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./github-runner:/tmp/github-runner
